# Generated by Django 2.2.2 on 2020-01-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_number', models.BigIntegerField(blank=True, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('address', models.TextField()),
                ('aadhar_number', models.BigIntegerField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
