# Generated by Django 3.0.4 on 2020-03-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isGSTClient',
            field=models.BooleanField(default=False),
        ),
    ]
