# Generated by Django 2.2.2 on 2020-01-20 16:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 1, 20, 16, 44, 3, 82504))),
                ('value', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(max_length=30)),
                ('card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('for_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Client')),
            ],
        ),
    ]
