# Generated by Django 3.0.4 on 2020-03-06 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200305_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdata',
            name='dated',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 3, 6, 14, 28, 27, 843179)),
        ),
    ]
