# Generated by Django 3.0.4 on 2020-03-05 18:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_auto_20200305_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 3, 5, 18, 19, 21, 276071))),
                ('to_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 3, 5, 18, 19, 21, 276071))),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Client')),
                ('employee_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
    ]
