# Generated by Django 3.0.4 on 2020-03-06 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_auto_20200306_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdata',
            name='from_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 3, 6, 17, 18, 36, 993021)),
        ),
        migrations.AlterField(
            model_name='reportdata',
            name='to_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 3, 6, 17, 18, 36, 993021)),
        ),
    ]
