# Generated by Django 2.2.5 on 2019-10-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='sendt_by',
            new_name='sent_by',
        ),
    ]
