# Generated by Django 2.2.5 on 2019-10-02 05:36

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='documents',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), blank=True, max_length=1600, null=True, size=0),
        ),
    ]
