# Generated by Django 3.0.4 on 2020-03-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='isGST_Service',
            field=models.BooleanField(default=False),
        ),
    ]
