# Generated by Django 2.2.5 on 2019-10-02 05:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191002_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='documents',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), blank=True, max_length=1200, null=True, size=10),
        ),
    ]
