# Generated by Django 2.2.5 on 2019-10-02 05:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20191002_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='documents',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), blank=True, max_length=3000, null=True, size=10),
        ),
    ]
