# Generated by Django 2.2.2 on 2020-01-20 16:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=20)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('due_date', models.DateField(null=True)),
                ('created', models.DateTimeField(null=True, verbose_name=datetime.datetime(2020, 1, 20, 16, 44, 3, 76461))),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 1, 20, 16, 44, 3, 76461))),
                ('charges', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
