# Generated by Django 2.2.5 on 2019-10-02 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191002_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 10, 2, 5, 7, 12, 655362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 10, 2, 5, 7, 12, 655362, tzinfo=utc)),
        ),
    ]
