# Generated by Django 3.0.4 on 2020-03-06 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gstClient.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_client_isgstclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_type', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GSTClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.TextField(null=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), gstClient.models.max_value_current_year], verbose_name='year')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='client.Client')),
                ('gst_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gstClient.GSTType')),
            ],
        ),
    ]
