# Generated by Django 3.0.4 on 2020-03-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsttype',
            name='gst_type',
            field=models.CharField(max_length=20),
        ),
    ]
