# Generated by Django 2.2.2 on 2020-01-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('attachment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task'),
        ),
    ]
