# Generated by Django 3.0.4 on 2020-03-05 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200211_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2020, 3, 5, 18, 19, 20, 994858)),
        ),
    ]
