# Generated by Django 2.2.5 on 2019-10-02 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191002_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 10, 2, 5, 42, 36, 903343, tzinfo=utc)),
        ),
    ]
