# Generated by Django 2.2.5 on 2019-10-02 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20191002_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 10, 2, 13, 15, 6, 150773)),
        ),
    ]
